# Generated by Django 3.2.5 on 2021-07-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assistent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden_number', models.IntegerField()),
                ('all_hidden_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Psychic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_guss', models.IntegerField()),
            ],
        ),
    ]
