# Generated by Django 3.2.5 on 2021-07-11 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistent',
            name='all_hidden_number',
        ),
        migrations.RemoveField(
            model_name='psychic',
            name='num_guss',
        ),
        migrations.AddField(
            model_name='psychic',
            name='name_p',
            field=models.CharField(default='Certain', max_length=20),
        ),
    ]
