# Generated by Django 3.2.5 on 2021-07-11 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psy', '0002_auto_20210711_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistent',
            name='hidden_number',
        ),
    ]
