# Generated by Django 3.2.5 on 2021-07-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psy', '0004_assistent_hidden_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistent',
            name='hidden_number',
            field=models.IntegerField(default=0),
        ),
    ]
