# Generated by Django 3.2.5 on 2021-07-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psy', '0008_rename_hidden_number_assistent_hidden'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assistent',
            old_name='hidden',
            new_name='all_hidden_number',
        ),
        migrations.AddField(
            model_name='assistent',
            name='hidden_number',
            field=models.IntegerField(default=0),
        ),
    ]
