# Generated by Django 3.2.5 on 2021-07-11 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psy', '0010_auto_20210711_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistent',
            name='all_hidden_number',
        ),
    ]
