# Generated by Django 3.2.5 on 2021-07-11 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psy', '0012_remove_assistent_hidden_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assistent',
        ),
        migrations.DeleteModel(
            name='Psychic',
        ),
    ]
