# Generated by Django 3.2.5 on 2021-07-11 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psy', '0007_assistent_hidden_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assistent',
            old_name='hidden_number',
            new_name='hidden',
        ),
    ]
