# Generated by Django 3.2.5 on 2021-07-11 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psy', '0011_remove_assistent_all_hidden_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistent',
            name='hidden_number',
        ),
    ]
