# Generated by Django 3.2.5 on 2021-07-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psy', '0009_auto_20210711_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistent',
            name='all_hidden_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='assistent',
            name='hidden_number',
            field=models.IntegerField(),
        ),
    ]
